// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/iwinder/qingyucms/app/qycms_user/internal/biz"
	"github.com/iwinder/qingyucms/app/qycms_user/internal/conf"
	"github.com/iwinder/qingyucms/app/qycms_user/internal/data/db"
	"github.com/iwinder/qingyucms/app/qycms_user/internal/server"
	"github.com/iwinder/qingyucms/app/qycms_user/internal/service"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, qycms *conf.Qycms, data *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	dbData, cleanup, err := db.NewData(data, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := db.NewUserRepo(dbData, logger)
	userUsecase := biz.NewGreeterUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, qycms)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
