// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.1
// source: api/qycms_bff/admin/v1/qy_admin_article.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQyAdminArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateQyAdminArticleRequest) Reset() {
	*x = CreateQyAdminArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQyAdminArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQyAdminArticleRequest) ProtoMessage() {}

func (x *CreateQyAdminArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQyAdminArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateQyAdminArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{0}
}

type CreateQyAdminArticleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateQyAdminArticleReply) Reset() {
	*x = CreateQyAdminArticleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQyAdminArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQyAdminArticleReply) ProtoMessage() {}

func (x *CreateQyAdminArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQyAdminArticleReply.ProtoReflect.Descriptor instead.
func (*CreateQyAdminArticleReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{1}
}

type UpdateQyAdminArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateQyAdminArticleRequest) Reset() {
	*x = UpdateQyAdminArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyAdminArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyAdminArticleRequest) ProtoMessage() {}

func (x *UpdateQyAdminArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyAdminArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateQyAdminArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{2}
}

type UpdateQyAdminArticleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateQyAdminArticleReply) Reset() {
	*x = UpdateQyAdminArticleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyAdminArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyAdminArticleReply) ProtoMessage() {}

func (x *UpdateQyAdminArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyAdminArticleReply.ProtoReflect.Descriptor instead.
func (*UpdateQyAdminArticleReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{3}
}

type DeleteQyAdminArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQyAdminArticleRequest) Reset() {
	*x = DeleteQyAdminArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQyAdminArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQyAdminArticleRequest) ProtoMessage() {}

func (x *DeleteQyAdminArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQyAdminArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteQyAdminArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{4}
}

type DeleteQyAdminArticleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQyAdminArticleReply) Reset() {
	*x = DeleteQyAdminArticleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQyAdminArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQyAdminArticleReply) ProtoMessage() {}

func (x *DeleteQyAdminArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQyAdminArticleReply.ProtoReflect.Descriptor instead.
func (*DeleteQyAdminArticleReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{5}
}

type GetQyAdminArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQyAdminArticleRequest) Reset() {
	*x = GetQyAdminArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQyAdminArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQyAdminArticleRequest) ProtoMessage() {}

func (x *GetQyAdminArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQyAdminArticleRequest.ProtoReflect.Descriptor instead.
func (*GetQyAdminArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{6}
}

type GetQyAdminArticleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQyAdminArticleReply) Reset() {
	*x = GetQyAdminArticleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQyAdminArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQyAdminArticleReply) ProtoMessage() {}

func (x *GetQyAdminArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQyAdminArticleReply.ProtoReflect.Descriptor instead.
func (*GetQyAdminArticleReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{7}
}

type ListQyAdminArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQyAdminArticleRequest) Reset() {
	*x = ListQyAdminArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyAdminArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyAdminArticleRequest) ProtoMessage() {}

func (x *ListQyAdminArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyAdminArticleRequest.ProtoReflect.Descriptor instead.
func (*ListQyAdminArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{8}
}

type ListQyAdminArticleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQyAdminArticleReply) Reset() {
	*x = ListQyAdminArticleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyAdminArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyAdminArticleReply) ProtoMessage() {}

func (x *ListQyAdminArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyAdminArticleReply.ProtoReflect.Descriptor instead.
func (*ListQyAdminArticleReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP(), []int{9}
}

var File_api_qycms_bff_admin_v1_qy_admin_article_proto protoreflect.FileDescriptor

var file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x79, 0x5f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x1d, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b,
	0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x51, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1b, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19,
	0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x81, 0x05, 0x0a, 0x0e, 0x51, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x7e, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73,
	0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x7e, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73,
	0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x7e, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73,
	0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x75, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66,
	0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f,
	0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x78, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x52, 0x0a,
	0x16, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x77, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x71, 0x69,
	0x6e, 0x67, 0x79, 0x75, 0x63, 0x6d, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x79, 0x63, 0x6d,
	0x73, 0x5f, 0x62, 0x66, 0x66, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescOnce sync.Once
	file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescData = file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDesc
)

func file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescGZIP() []byte {
	file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescOnce.Do(func() {
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescData)
	})
	return file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDescData
}

var file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_qycms_bff_admin_v1_qy_admin_article_proto_goTypes = []interface{}{
	(*CreateQyAdminArticleRequest)(nil), // 0: api.qycms_bff.admin.v1.CreateQyAdminArticleRequest
	(*CreateQyAdminArticleReply)(nil),   // 1: api.qycms_bff.admin.v1.CreateQyAdminArticleReply
	(*UpdateQyAdminArticleRequest)(nil), // 2: api.qycms_bff.admin.v1.UpdateQyAdminArticleRequest
	(*UpdateQyAdminArticleReply)(nil),   // 3: api.qycms_bff.admin.v1.UpdateQyAdminArticleReply
	(*DeleteQyAdminArticleRequest)(nil), // 4: api.qycms_bff.admin.v1.DeleteQyAdminArticleRequest
	(*DeleteQyAdminArticleReply)(nil),   // 5: api.qycms_bff.admin.v1.DeleteQyAdminArticleReply
	(*GetQyAdminArticleRequest)(nil),    // 6: api.qycms_bff.admin.v1.GetQyAdminArticleRequest
	(*GetQyAdminArticleReply)(nil),      // 7: api.qycms_bff.admin.v1.GetQyAdminArticleReply
	(*ListQyAdminArticleRequest)(nil),   // 8: api.qycms_bff.admin.v1.ListQyAdminArticleRequest
	(*ListQyAdminArticleReply)(nil),     // 9: api.qycms_bff.admin.v1.ListQyAdminArticleReply
}
var file_api_qycms_bff_admin_v1_qy_admin_article_proto_depIdxs = []int32{
	0, // 0: api.qycms_bff.admin.v1.QyAdminArticle.CreateQyAdminArticle:input_type -> api.qycms_bff.admin.v1.CreateQyAdminArticleRequest
	2, // 1: api.qycms_bff.admin.v1.QyAdminArticle.UpdateQyAdminArticle:input_type -> api.qycms_bff.admin.v1.UpdateQyAdminArticleRequest
	4, // 2: api.qycms_bff.admin.v1.QyAdminArticle.DeleteQyAdminArticle:input_type -> api.qycms_bff.admin.v1.DeleteQyAdminArticleRequest
	6, // 3: api.qycms_bff.admin.v1.QyAdminArticle.GetQyAdminArticle:input_type -> api.qycms_bff.admin.v1.GetQyAdminArticleRequest
	8, // 4: api.qycms_bff.admin.v1.QyAdminArticle.ListQyAdminArticle:input_type -> api.qycms_bff.admin.v1.ListQyAdminArticleRequest
	1, // 5: api.qycms_bff.admin.v1.QyAdminArticle.CreateQyAdminArticle:output_type -> api.qycms_bff.admin.v1.CreateQyAdminArticleReply
	3, // 6: api.qycms_bff.admin.v1.QyAdminArticle.UpdateQyAdminArticle:output_type -> api.qycms_bff.admin.v1.UpdateQyAdminArticleReply
	5, // 7: api.qycms_bff.admin.v1.QyAdminArticle.DeleteQyAdminArticle:output_type -> api.qycms_bff.admin.v1.DeleteQyAdminArticleReply
	7, // 8: api.qycms_bff.admin.v1.QyAdminArticle.GetQyAdminArticle:output_type -> api.qycms_bff.admin.v1.GetQyAdminArticleReply
	9, // 9: api.qycms_bff.admin.v1.QyAdminArticle.ListQyAdminArticle:output_type -> api.qycms_bff.admin.v1.ListQyAdminArticleReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_qycms_bff_admin_v1_qy_admin_article_proto_init() }
func file_api_qycms_bff_admin_v1_qy_admin_article_proto_init() {
	if File_api_qycms_bff_admin_v1_qy_admin_article_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQyAdminArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQyAdminArticleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyAdminArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyAdminArticleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQyAdminArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQyAdminArticleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQyAdminArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQyAdminArticleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyAdminArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyAdminArticleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_qycms_bff_admin_v1_qy_admin_article_proto_goTypes,
		DependencyIndexes: file_api_qycms_bff_admin_v1_qy_admin_article_proto_depIdxs,
		MessageInfos:      file_api_qycms_bff_admin_v1_qy_admin_article_proto_msgTypes,
	}.Build()
	File_api_qycms_bff_admin_v1_qy_admin_article_proto = out.File
	file_api_qycms_bff_admin_v1_qy_admin_article_proto_rawDesc = nil
	file_api_qycms_bff_admin_v1_qy_admin_article_proto_goTypes = nil
	file_api_qycms_bff_admin_v1_qy_admin_article_proto_depIdxs = nil
}
