// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.1
// source: api/qycms_bff/admin/v1/qy_admin_home.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQyAdminHomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateQyAdminHomeRequest) Reset() {
	*x = CreateQyAdminHomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQyAdminHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQyAdminHomeRequest) ProtoMessage() {}

func (x *CreateQyAdminHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQyAdminHomeRequest.ProtoReflect.Descriptor instead.
func (*CreateQyAdminHomeRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{0}
}

type CreateQyAdminHomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateQyAdminHomeReply) Reset() {
	*x = CreateQyAdminHomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQyAdminHomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQyAdminHomeReply) ProtoMessage() {}

func (x *CreateQyAdminHomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQyAdminHomeReply.ProtoReflect.Descriptor instead.
func (*CreateQyAdminHomeReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{1}
}

type UpdateQyAdminHomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateQyAdminHomeRequest) Reset() {
	*x = UpdateQyAdminHomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyAdminHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyAdminHomeRequest) ProtoMessage() {}

func (x *UpdateQyAdminHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyAdminHomeRequest.ProtoReflect.Descriptor instead.
func (*UpdateQyAdminHomeRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{2}
}

type UpdateQyAdminHomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateQyAdminHomeReply) Reset() {
	*x = UpdateQyAdminHomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyAdminHomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyAdminHomeReply) ProtoMessage() {}

func (x *UpdateQyAdminHomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyAdminHomeReply.ProtoReflect.Descriptor instead.
func (*UpdateQyAdminHomeReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{3}
}

type DeleteQyAdminHomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQyAdminHomeRequest) Reset() {
	*x = DeleteQyAdminHomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQyAdminHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQyAdminHomeRequest) ProtoMessage() {}

func (x *DeleteQyAdminHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQyAdminHomeRequest.ProtoReflect.Descriptor instead.
func (*DeleteQyAdminHomeRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{4}
}

type DeleteQyAdminHomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQyAdminHomeReply) Reset() {
	*x = DeleteQyAdminHomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQyAdminHomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQyAdminHomeReply) ProtoMessage() {}

func (x *DeleteQyAdminHomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQyAdminHomeReply.ProtoReflect.Descriptor instead.
func (*DeleteQyAdminHomeReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{5}
}

type GetQyAdminHomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQyAdminHomeRequest) Reset() {
	*x = GetQyAdminHomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQyAdminHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQyAdminHomeRequest) ProtoMessage() {}

func (x *GetQyAdminHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQyAdminHomeRequest.ProtoReflect.Descriptor instead.
func (*GetQyAdminHomeRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{6}
}

type GetQyAdminHomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQyAdminHomeReply) Reset() {
	*x = GetQyAdminHomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQyAdminHomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQyAdminHomeReply) ProtoMessage() {}

func (x *GetQyAdminHomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQyAdminHomeReply.ProtoReflect.Descriptor instead.
func (*GetQyAdminHomeReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{7}
}

type ListQyAdminHomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQyAdminHomeRequest) Reset() {
	*x = ListQyAdminHomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyAdminHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyAdminHomeRequest) ProtoMessage() {}

func (x *ListQyAdminHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyAdminHomeRequest.ProtoReflect.Descriptor instead.
func (*ListQyAdminHomeRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{8}
}

type ListQyAdminHomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQyAdminHomeReply) Reset() {
	*x = ListQyAdminHomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyAdminHomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyAdminHomeReply) ProtoMessage() {}

func (x *ListQyAdminHomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyAdminHomeReply.ProtoReflect.Descriptor instead.
func (*ListQyAdminHomeReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP(), []int{9}
}

var File_api_qycms_bff_admin_v1_qy_admin_home_proto protoreflect.FileDescriptor

var file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x79, 0x5f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70,
	0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a,
	0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xba, 0x07, 0x0a, 0x0b, 0x51, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0xb4, 0x01, 0x0a, 0x21, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4a, 0x6f, 0x62,
	0x73, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x30, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2d,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x27, 0x22, 0x25, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0xa7, 0x01,
	0x0a, 0x1a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x61, 0x70, 0x4a, 0x6f,
	0x62, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x30, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x22, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x4d, 0x61, 0x70, 0x12, 0xb6, 0x01, 0x0a, 0x22, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4a,
	0x6f, 0x62, 0x73, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x30,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x22, 0x26, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x2f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0xb1, 0x01, 0x0a, 0x22, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x6f, 0x4e, 0x6f, 0x74, 0x53,
	0x65, 0x6e, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x51, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79,
	0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x23, 0x22, 0x21, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x6f, 0x4e, 0x6f, 0x74,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x6c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63,
	0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d,
	0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x6f, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d,
	0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d,
	0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x52, 0x0a, 0x16, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73,
	0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a,
	0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x77, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x2f, 0x71, 0x69, 0x6e, 0x67, 0x79, 0x75, 0x63, 0x6d, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescOnce sync.Once
	file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescData = file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDesc
)

func file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescGZIP() []byte {
	file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescOnce.Do(func() {
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescData)
	})
	return file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDescData
}

var file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_qycms_bff_admin_v1_qy_admin_home_proto_goTypes = []interface{}{
	(*CreateQyAdminHomeRequest)(nil), // 0: api.qycms_bff.admin.v1.CreateQyAdminHomeRequest
	(*CreateQyAdminHomeReply)(nil),   // 1: api.qycms_bff.admin.v1.CreateQyAdminHomeReply
	(*UpdateQyAdminHomeRequest)(nil), // 2: api.qycms_bff.admin.v1.UpdateQyAdminHomeRequest
	(*UpdateQyAdminHomeReply)(nil),   // 3: api.qycms_bff.admin.v1.UpdateQyAdminHomeReply
	(*DeleteQyAdminHomeRequest)(nil), // 4: api.qycms_bff.admin.v1.DeleteQyAdminHomeRequest
	(*DeleteQyAdminHomeReply)(nil),   // 5: api.qycms_bff.admin.v1.DeleteQyAdminHomeReply
	(*GetQyAdminHomeRequest)(nil),    // 6: api.qycms_bff.admin.v1.GetQyAdminHomeRequest
	(*GetQyAdminHomeReply)(nil),      // 7: api.qycms_bff.admin.v1.GetQyAdminHomeReply
	(*ListQyAdminHomeRequest)(nil),   // 8: api.qycms_bff.admin.v1.ListQyAdminHomeRequest
	(*ListQyAdminHomeReply)(nil),     // 9: api.qycms_bff.admin.v1.ListQyAdminHomeReply
}
var file_api_qycms_bff_admin_v1_qy_admin_home_proto_depIdxs = []int32{
	0, // 0: api.qycms_bff.admin.v1.QyAdminHome.UpdateContentCountJobsQyAdminHome:input_type -> api.qycms_bff.admin.v1.CreateQyAdminHomeRequest
	0, // 1: api.qycms_bff.admin.v1.QyAdminHome.GeneratorMapJobQyAdminHome:input_type -> api.qycms_bff.admin.v1.CreateQyAdminHomeRequest
	0, // 2: api.qycms_bff.admin.v1.QyAdminHome.UpdateAllPostsCountJobsQyAdminHome:input_type -> api.qycms_bff.admin.v1.CreateQyAdminHomeRequest
	0, // 3: api.qycms_bff.admin.v1.QyAdminHome.EmailToNotSendCountJobsQyAdminHome:input_type -> api.qycms_bff.admin.v1.CreateQyAdminHomeRequest
	6, // 4: api.qycms_bff.admin.v1.QyAdminHome.GetQyAdminHome:input_type -> api.qycms_bff.admin.v1.GetQyAdminHomeRequest
	8, // 5: api.qycms_bff.admin.v1.QyAdminHome.ListQyAdminHome:input_type -> api.qycms_bff.admin.v1.ListQyAdminHomeRequest
	1, // 6: api.qycms_bff.admin.v1.QyAdminHome.UpdateContentCountJobsQyAdminHome:output_type -> api.qycms_bff.admin.v1.CreateQyAdminHomeReply
	1, // 7: api.qycms_bff.admin.v1.QyAdminHome.GeneratorMapJobQyAdminHome:output_type -> api.qycms_bff.admin.v1.CreateQyAdminHomeReply
	1, // 8: api.qycms_bff.admin.v1.QyAdminHome.UpdateAllPostsCountJobsQyAdminHome:output_type -> api.qycms_bff.admin.v1.CreateQyAdminHomeReply
	1, // 9: api.qycms_bff.admin.v1.QyAdminHome.EmailToNotSendCountJobsQyAdminHome:output_type -> api.qycms_bff.admin.v1.CreateQyAdminHomeReply
	7, // 10: api.qycms_bff.admin.v1.QyAdminHome.GetQyAdminHome:output_type -> api.qycms_bff.admin.v1.GetQyAdminHomeReply
	9, // 11: api.qycms_bff.admin.v1.QyAdminHome.ListQyAdminHome:output_type -> api.qycms_bff.admin.v1.ListQyAdminHomeReply
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_qycms_bff_admin_v1_qy_admin_home_proto_init() }
func file_api_qycms_bff_admin_v1_qy_admin_home_proto_init() {
	if File_api_qycms_bff_admin_v1_qy_admin_home_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQyAdminHomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQyAdminHomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyAdminHomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyAdminHomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQyAdminHomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQyAdminHomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQyAdminHomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQyAdminHomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyAdminHomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyAdminHomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_qycms_bff_admin_v1_qy_admin_home_proto_goTypes,
		DependencyIndexes: file_api_qycms_bff_admin_v1_qy_admin_home_proto_depIdxs,
		MessageInfos:      file_api_qycms_bff_admin_v1_qy_admin_home_proto_msgTypes,
	}.Build()
	File_api_qycms_bff_admin_v1_qy_admin_home_proto = out.File
	file_api_qycms_bff_admin_v1_qy_admin_home_proto_rawDesc = nil
	file_api_qycms_bff_admin_v1_qy_admin_home_proto_goTypes = nil
	file_api_qycms_bff_admin_v1_qy_admin_home_proto_depIdxs = nil
}
