// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.1
// source: api/qycms_bff/admin/v1/qy_admin_file.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilePageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current   int64 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	PageSize  int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Total     int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Pages     int64 `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	FirstFlag bool  `protobuf:"varint,5,opt,name=firstFlag,proto3" json:"firstFlag,omitempty"`
	LastFlag  bool  `protobuf:"varint,6,opt,name=lastFlag,proto3" json:"lastFlag,omitempty"`
}

func (x *FilePageInfo) Reset() {
	*x = FilePageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePageInfo) ProtoMessage() {}

func (x *FilePageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePageInfo.ProtoReflect.Descriptor instead.
func (*FilePageInfo) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{0}
}

func (x *FilePageInfo) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *FilePageInfo) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FilePageInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FilePageInfo) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *FilePageInfo) GetFirstFlag() bool {
	if x != nil {
		return x.FirstFlag
	}
	return false
}

func (x *FilePageInfo) GetLastFlag() bool {
	if x != nil {
		return x.LastFlag
	}
	return false
}

type FileLibTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Identifier int32  `protobuf:"varint,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Ftype      string `protobuf:"bytes,4,opt,name=ftype,proto3" json:"ftype,omitempty"`
	StatusFlag int32  `protobuf:"varint,5,opt,name=statusFlag,proto3" json:"statusFlag,omitempty"`
}

func (x *FileLibTypeResponse) Reset() {
	*x = FileLibTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileLibTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLibTypeResponse) ProtoMessage() {}

func (x *FileLibTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLibTypeResponse.ProtoReflect.Descriptor instead.
func (*FileLibTypeResponse) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileLibTypeResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileLibTypeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileLibTypeResponse) GetIdentifier() int32 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *FileLibTypeResponse) GetFtype() string {
	if x != nil {
		return x.Ftype
	}
	return ""
}

func (x *FileLibTypeResponse) GetStatusFlag() int32 {
	if x != nil {
		return x.StatusFlag
	}
	return 0
}

type UpdateQyAdminFileLibTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Identifier int32  `protobuf:"varint,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Ftype      string `protobuf:"bytes,4,opt,name=ftype,proto3" json:"ftype,omitempty"`
	StatusFlag int32  `protobuf:"varint,5,opt,name=statusFlag,proto3" json:"statusFlag,omitempty"`
}

func (x *UpdateQyAdminFileLibTypeRequest) Reset() {
	*x = UpdateQyAdminFileLibTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyAdminFileLibTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyAdminFileLibTypeRequest) ProtoMessage() {}

func (x *UpdateQyAdminFileLibTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyAdminFileLibTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateQyAdminFileLibTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateQyAdminFileLibTypeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateQyAdminFileLibTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateQyAdminFileLibTypeRequest) GetIdentifier() int32 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *UpdateQyAdminFileLibTypeRequest) GetFtype() string {
	if x != nil {
		return x.Ftype
	}
	return ""
}

func (x *UpdateQyAdminFileLibTypeRequest) GetStatusFlag() int32 {
	if x != nil {
		return x.StatusFlag
	}
	return 0
}

type UpdateQyAdminFileLibTypeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateQyAdminFileLibTypeReply) Reset() {
	*x = UpdateQyAdminFileLibTypeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyAdminFileLibTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyAdminFileLibTypeReply) ProtoMessage() {}

func (x *UpdateQyAdminFileLibTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyAdminFileLibTypeReply.ProtoReflect.Descriptor instead.
func (*UpdateQyAdminFileLibTypeReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateQyAdminFileLibTypeReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListQyAdminFileLibTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current   int64  `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	PageSize  int64  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Total     int64  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Pages     int64  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	FirstFlag bool   `protobuf:"varint,5,opt,name=firstFlag,proto3" json:"firstFlag,omitempty"`
	LastFlag  bool   `protobuf:"varint,6,opt,name=lastFlag,proto3" json:"lastFlag,omitempty"`
	Name      string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListQyAdminFileLibTypeRequest) Reset() {
	*x = ListQyAdminFileLibTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyAdminFileLibTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyAdminFileLibTypeRequest) ProtoMessage() {}

func (x *ListQyAdminFileLibTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyAdminFileLibTypeRequest.ProtoReflect.Descriptor instead.
func (*ListQyAdminFileLibTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{4}
}

func (x *ListQyAdminFileLibTypeRequest) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ListQyAdminFileLibTypeRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListQyAdminFileLibTypeRequest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListQyAdminFileLibTypeRequest) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *ListQyAdminFileLibTypeRequest) GetFirstFlag() bool {
	if x != nil {
		return x.FirstFlag
	}
	return false
}

func (x *ListQyAdminFileLibTypeRequest) GetLastFlag() bool {
	if x != nil {
		return x.LastFlag
	}
	return false
}

func (x *ListQyAdminFileLibTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListQyAdminFileLibTypeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageInfo *FilePageInfo          `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	Items    []*FileLibTypeResponse `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListQyAdminFileLibTypeReply) Reset() {
	*x = ListQyAdminFileLibTypeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyAdminFileLibTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyAdminFileLibTypeReply) ProtoMessage() {}

func (x *ListQyAdminFileLibTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyAdminFileLibTypeReply.ProtoReflect.Descriptor instead.
func (*ListQyAdminFileLibTypeReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{5}
}

func (x *ListQyAdminFileLibTypeReply) GetPageInfo() *FilePageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ListQyAdminFileLibTypeReply) GetItems() []*FileLibTypeResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateQyAdminFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateQyAdminFileRequest) Reset() {
	*x = CreateQyAdminFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQyAdminFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQyAdminFileRequest) ProtoMessage() {}

func (x *CreateQyAdminFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQyAdminFileRequest.ProtoReflect.Descriptor instead.
func (*CreateQyAdminFileRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{6}
}

type CreateQyAdminFileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateQyAdminFileReply) Reset() {
	*x = CreateQyAdminFileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQyAdminFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQyAdminFileReply) ProtoMessage() {}

func (x *CreateQyAdminFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQyAdminFileReply.ProtoReflect.Descriptor instead.
func (*CreateQyAdminFileReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{7}
}

type UpdateQyAdminFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateQyAdminFileRequest) Reset() {
	*x = UpdateQyAdminFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyAdminFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyAdminFileRequest) ProtoMessage() {}

func (x *UpdateQyAdminFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyAdminFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateQyAdminFileRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{8}
}

type UpdateQyAdminFileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateQyAdminFileReply) Reset() {
	*x = UpdateQyAdminFileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyAdminFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyAdminFileReply) ProtoMessage() {}

func (x *UpdateQyAdminFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyAdminFileReply.ProtoReflect.Descriptor instead.
func (*UpdateQyAdminFileReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{9}
}

type DeleteQyAdminFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQyAdminFileRequest) Reset() {
	*x = DeleteQyAdminFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQyAdminFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQyAdminFileRequest) ProtoMessage() {}

func (x *DeleteQyAdminFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQyAdminFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteQyAdminFileRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{10}
}

type DeleteQyAdminFileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQyAdminFileReply) Reset() {
	*x = DeleteQyAdminFileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQyAdminFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQyAdminFileReply) ProtoMessage() {}

func (x *DeleteQyAdminFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQyAdminFileReply.ProtoReflect.Descriptor instead.
func (*DeleteQyAdminFileReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{11}
}

type GetQyAdminFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQyAdminFileRequest) Reset() {
	*x = GetQyAdminFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQyAdminFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQyAdminFileRequest) ProtoMessage() {}

func (x *GetQyAdminFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQyAdminFileRequest.ProtoReflect.Descriptor instead.
func (*GetQyAdminFileRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{12}
}

type GetQyAdminFileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQyAdminFileReply) Reset() {
	*x = GetQyAdminFileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQyAdminFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQyAdminFileReply) ProtoMessage() {}

func (x *GetQyAdminFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQyAdminFileReply.ProtoReflect.Descriptor instead.
func (*GetQyAdminFileReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{13}
}

type ListQyAdminFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQyAdminFileRequest) Reset() {
	*x = ListQyAdminFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyAdminFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyAdminFileRequest) ProtoMessage() {}

func (x *ListQyAdminFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyAdminFileRequest.ProtoReflect.Descriptor instead.
func (*ListQyAdminFileRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{14}
}

type ListQyAdminFileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQyAdminFileReply) Reset() {
	*x = ListQyAdminFileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyAdminFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyAdminFileReply) ProtoMessage() {}

func (x *ListQyAdminFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyAdminFileReply.ProtoReflect.Descriptor instead.
func (*ListQyAdminFileReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP(), []int{15}
}

var File_api_qycms_bff_admin_v1_qy_admin_file_proto protoreflect.FileDescriptor

var file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x79, 0x5f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70,
	0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x22, 0xaa, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x46, 0x6c, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x6c, 0x61,
	0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x6c, 0x61,
	0x67, 0x22, 0x8f, 0x01, 0x0a, 0x13, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x62, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46, 0x6c, 0x61,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46,
	0x6c, 0x61, 0x67, 0x22, 0x9b, 0x01, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x62, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46, 0x6c, 0x61, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46, 0x6c, 0x61,
	0x67, 0x22, 0x2f, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x22, 0xcf, 0x01, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x46,
	0x6c, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x46, 0x6c, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x6c, 0x61, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x6c, 0x61, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x62, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63,
	0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x41, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d,
	0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x4c, 0x69, 0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51,
	0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51,
	0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xe5, 0x06,
	0x0a, 0x0b, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x8a, 0x01,
	0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46,
	0x69, 0x6c, 0x65, 0x4c, 0x69, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x37, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f,
	0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69,
	0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x84, 0x01, 0x0a, 0x16, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69,
	0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x35, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d,
	0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69,
	0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x75, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63,
	0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71,
	0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x75, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x30, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51,
	0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x75, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73,
	0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63,
	0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x51, 0x79, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71,
	0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79,
	0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x6f, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79,
	0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79,
	0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x52, 0x0a, 0x16, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63,
	0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x50,
	0x01, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x77,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x71, 0x69, 0x6e, 0x67, 0x79, 0x75, 0x63, 0x6d, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescOnce sync.Once
	file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescData = file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDesc
)

func file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescGZIP() []byte {
	file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescOnce.Do(func() {
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescData)
	})
	return file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDescData
}

var file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_qycms_bff_admin_v1_qy_admin_file_proto_goTypes = []interface{}{
	(*FilePageInfo)(nil),                    // 0: api.qycms_bff.admin.v1.FilePageInfo
	(*FileLibTypeResponse)(nil),             // 1: api.qycms_bff.admin.v1.FileLibTypeResponse
	(*UpdateQyAdminFileLibTypeRequest)(nil), // 2: api.qycms_bff.admin.v1.UpdateQyAdminFileLibTypeRequest
	(*UpdateQyAdminFileLibTypeReply)(nil),   // 3: api.qycms_bff.admin.v1.UpdateQyAdminFileLibTypeReply
	(*ListQyAdminFileLibTypeRequest)(nil),   // 4: api.qycms_bff.admin.v1.ListQyAdminFileLibTypeRequest
	(*ListQyAdminFileLibTypeReply)(nil),     // 5: api.qycms_bff.admin.v1.ListQyAdminFileLibTypeReply
	(*CreateQyAdminFileRequest)(nil),        // 6: api.qycms_bff.admin.v1.CreateQyAdminFileRequest
	(*CreateQyAdminFileReply)(nil),          // 7: api.qycms_bff.admin.v1.CreateQyAdminFileReply
	(*UpdateQyAdminFileRequest)(nil),        // 8: api.qycms_bff.admin.v1.UpdateQyAdminFileRequest
	(*UpdateQyAdminFileReply)(nil),          // 9: api.qycms_bff.admin.v1.UpdateQyAdminFileReply
	(*DeleteQyAdminFileRequest)(nil),        // 10: api.qycms_bff.admin.v1.DeleteQyAdminFileRequest
	(*DeleteQyAdminFileReply)(nil),          // 11: api.qycms_bff.admin.v1.DeleteQyAdminFileReply
	(*GetQyAdminFileRequest)(nil),           // 12: api.qycms_bff.admin.v1.GetQyAdminFileRequest
	(*GetQyAdminFileReply)(nil),             // 13: api.qycms_bff.admin.v1.GetQyAdminFileReply
	(*ListQyAdminFileRequest)(nil),          // 14: api.qycms_bff.admin.v1.ListQyAdminFileRequest
	(*ListQyAdminFileReply)(nil),            // 15: api.qycms_bff.admin.v1.ListQyAdminFileReply
}
var file_api_qycms_bff_admin_v1_qy_admin_file_proto_depIdxs = []int32{
	0,  // 0: api.qycms_bff.admin.v1.ListQyAdminFileLibTypeReply.pageInfo:type_name -> api.qycms_bff.admin.v1.FilePageInfo
	1,  // 1: api.qycms_bff.admin.v1.ListQyAdminFileLibTypeReply.items:type_name -> api.qycms_bff.admin.v1.FileLibTypeResponse
	2,  // 2: api.qycms_bff.admin.v1.QyAdminFile.UpdateQyAdminFileLibType:input_type -> api.qycms_bff.admin.v1.UpdateQyAdminFileLibTypeRequest
	4,  // 3: api.qycms_bff.admin.v1.QyAdminFile.ListQyAdminFileLibType:input_type -> api.qycms_bff.admin.v1.ListQyAdminFileLibTypeRequest
	6,  // 4: api.qycms_bff.admin.v1.QyAdminFile.CreateQyAdminFile:input_type -> api.qycms_bff.admin.v1.CreateQyAdminFileRequest
	8,  // 5: api.qycms_bff.admin.v1.QyAdminFile.UpdateQyAdminFile:input_type -> api.qycms_bff.admin.v1.UpdateQyAdminFileRequest
	10, // 6: api.qycms_bff.admin.v1.QyAdminFile.DeleteQyAdminFile:input_type -> api.qycms_bff.admin.v1.DeleteQyAdminFileRequest
	12, // 7: api.qycms_bff.admin.v1.QyAdminFile.GetQyAdminFile:input_type -> api.qycms_bff.admin.v1.GetQyAdminFileRequest
	14, // 8: api.qycms_bff.admin.v1.QyAdminFile.ListQyAdminFile:input_type -> api.qycms_bff.admin.v1.ListQyAdminFileRequest
	3,  // 9: api.qycms_bff.admin.v1.QyAdminFile.UpdateQyAdminFileLibType:output_type -> api.qycms_bff.admin.v1.UpdateQyAdminFileLibTypeReply
	5,  // 10: api.qycms_bff.admin.v1.QyAdminFile.ListQyAdminFileLibType:output_type -> api.qycms_bff.admin.v1.ListQyAdminFileLibTypeReply
	7,  // 11: api.qycms_bff.admin.v1.QyAdminFile.CreateQyAdminFile:output_type -> api.qycms_bff.admin.v1.CreateQyAdminFileReply
	9,  // 12: api.qycms_bff.admin.v1.QyAdminFile.UpdateQyAdminFile:output_type -> api.qycms_bff.admin.v1.UpdateQyAdminFileReply
	11, // 13: api.qycms_bff.admin.v1.QyAdminFile.DeleteQyAdminFile:output_type -> api.qycms_bff.admin.v1.DeleteQyAdminFileReply
	13, // 14: api.qycms_bff.admin.v1.QyAdminFile.GetQyAdminFile:output_type -> api.qycms_bff.admin.v1.GetQyAdminFileReply
	15, // 15: api.qycms_bff.admin.v1.QyAdminFile.ListQyAdminFile:output_type -> api.qycms_bff.admin.v1.ListQyAdminFileReply
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_qycms_bff_admin_v1_qy_admin_file_proto_init() }
func file_api_qycms_bff_admin_v1_qy_admin_file_proto_init() {
	if File_api_qycms_bff_admin_v1_qy_admin_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileLibTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyAdminFileLibTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyAdminFileLibTypeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyAdminFileLibTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyAdminFileLibTypeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQyAdminFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQyAdminFileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyAdminFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyAdminFileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQyAdminFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQyAdminFileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQyAdminFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQyAdminFileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyAdminFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyAdminFileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_qycms_bff_admin_v1_qy_admin_file_proto_goTypes,
		DependencyIndexes: file_api_qycms_bff_admin_v1_qy_admin_file_proto_depIdxs,
		MessageInfos:      file_api_qycms_bff_admin_v1_qy_admin_file_proto_msgTypes,
	}.Build()
	File_api_qycms_bff_admin_v1_qy_admin_file_proto = out.File
	file_api_qycms_bff_admin_v1_qy_admin_file_proto_rawDesc = nil
	file_api_qycms_bff_admin_v1_qy_admin_file_proto_goTypes = nil
	file_api_qycms_bff_admin_v1_qy_admin_file_proto_depIdxs = nil
}
