// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/iwinder/qingyucms/internal/qycms_blog/biz"
	"github.com/iwinder/qingyucms/internal/qycms_blog/conf"
	"github.com/iwinder/qingyucms/internal/qycms_blog/data/db"
	"github.com/iwinder/qingyucms/internal/qycms_blog/server"
	"github.com/iwinder/qingyucms/internal/qycms_blog/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, qycms *conf.Qycms, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dbData, cleanup, err := db.NewData(data, logger)
	if err != nil {
		return nil, nil, err
	}
	casbinData, err := db.NewCasbinData(dbData, auth, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepo := db.NewUserRepo(dbData, logger)
	roleRepo := db.NewRoleRepo(dbData, logger)
	casbinRuleRepo := db.NewCasbinRuleRepo(casbinData, logger)
	roleMenusRepo := db.NewRoleMenusRepo(dbData, logger)
	roleMenusUsecase := biz.NewRoleMenusUsecase(roleMenusRepo, logger)
	roleApiRepo := db.NewRoleApiRepo(dbData, logger)
	roleApiUsecase := biz.NewRoleApiUsecase(roleApiRepo, casbinRuleRepo, logger)
	roleUsecase := biz.NewRoleUsecase(roleRepo, casbinRuleRepo, roleMenusUsecase, roleApiUsecase, logger)
	userRoleRepo := db.NewUserRoleRepo(dbData, logger)
	userRoleUsecase := biz.NewUserRoleUsecase(userRoleRepo, casbinRuleRepo, logger)
	userUsecase := biz.NewUserUsecase(userRepo, roleUsecase, userRoleUsecase, logger)
	apiRepo := db.NewApiRepo(dbData, logger)
	apiGroupRepo := db.NewApiGroupRepo(dbData, logger)
	apiGroupUsecase := biz.NewApiGroupUsecase(apiGroupRepo, logger)
	apiUsecase := biz.NewApiUsecase(apiRepo, apiGroupUsecase, casbinRuleRepo, logger)
	menusAdminRepo := db.NewMenusAdminRepo(dbData, logger)
	menusAdminUsecase := biz.NewMenusAdminUsecase(menusAdminRepo, logger)
	fileLibTypeRepo := db.NewFileLibTypeRepo(dbData, logger)
	fileLibTypeUsecase := biz.NewFileLibTypeUsecase(fileLibTypeRepo, logger)
	fileLibConfigRepo := db.NewFileLibConfigRepo(dbData, logger)
	fileLibConfigUsecase := biz.NewFileLibConfigUsecase(fileLibConfigRepo, logger)
	fileLibRepo := db.NewFileLibRepo(dbData, logger)
	fileLibUsecase := biz.NewFileLibUsecase(fileLibRepo, logger)
	blogAdminUserService := service.NewBlogAdminUserService(userUsecase, roleUsecase, apiUsecase, roleMenusUsecase, apiGroupUsecase, menusAdminUsecase, roleApiUsecase, fileLibTypeUsecase, fileLibConfigUsecase, fileLibUsecase, qycms, auth)
	httpServer := server.NewHTTPServer(confServer, auth, casbinData, blogAdminUserService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
