// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/iwinder/qingyucms/app/qycms_blog/internal/biz"
	"github.com/iwinder/qingyucms/app/qycms_blog/internal/conf"
	"github.com/iwinder/qingyucms/app/qycms_blog/internal/data/db"
	"github.com/iwinder/qingyucms/app/qycms_blog/internal/server"
	"github.com/iwinder/qingyucms/app/qycms_blog/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := db.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := db.NewArticleRepo(dataData, logger)
	greeterUsecase := biz.NewArticleUsecase(greeterRepo, logger)
	greeterService := service.NewArticleService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
