// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.1
// source: api/qycms_bff/web/v1/qy_web_links.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebLinkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url         string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *WebLinkInfo) Reset() {
	*x = WebLinkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebLinkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebLinkInfo) ProtoMessage() {}

func (x *WebLinkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebLinkInfo.ProtoReflect.Descriptor instead.
func (*WebLinkInfo) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{0}
}

func (x *WebLinkInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebLinkInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebLinkInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebLinkInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type WebShortLinkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Identifier string `protobuf:"bytes,5,opt,name=identifier,proto3" json:"identifier,omitempty"`
}

func (x *WebShortLinkInfo) Reset() {
	*x = WebShortLinkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebShortLinkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebShortLinkInfo) ProtoMessage() {}

func (x *WebShortLinkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebShortLinkInfo.ProtoReflect.Descriptor instead.
func (*WebShortLinkInfo) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{1}
}

func (x *WebShortLinkInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebShortLinkInfo) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type CreateQyWebLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateQyWebLinksRequest) Reset() {
	*x = CreateQyWebLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQyWebLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQyWebLinksRequest) ProtoMessage() {}

func (x *CreateQyWebLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQyWebLinksRequest.ProtoReflect.Descriptor instead.
func (*CreateQyWebLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{2}
}

type CreateQyWebLinksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateQyWebLinksReply) Reset() {
	*x = CreateQyWebLinksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQyWebLinksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQyWebLinksReply) ProtoMessage() {}

func (x *CreateQyWebLinksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQyWebLinksReply.ProtoReflect.Descriptor instead.
func (*CreateQyWebLinksReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{3}
}

type UpdateQyWebLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateQyWebLinksRequest) Reset() {
	*x = UpdateQyWebLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyWebLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyWebLinksRequest) ProtoMessage() {}

func (x *UpdateQyWebLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyWebLinksRequest.ProtoReflect.Descriptor instead.
func (*UpdateQyWebLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{4}
}

type UpdateQyWebLinksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateQyWebLinksReply) Reset() {
	*x = UpdateQyWebLinksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQyWebLinksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQyWebLinksReply) ProtoMessage() {}

func (x *UpdateQyWebLinksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQyWebLinksReply.ProtoReflect.Descriptor instead.
func (*UpdateQyWebLinksReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{5}
}

type DeleteQyWebLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQyWebLinksRequest) Reset() {
	*x = DeleteQyWebLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQyWebLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQyWebLinksRequest) ProtoMessage() {}

func (x *DeleteQyWebLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQyWebLinksRequest.ProtoReflect.Descriptor instead.
func (*DeleteQyWebLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{6}
}

type DeleteQyWebLinksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQyWebLinksReply) Reset() {
	*x = DeleteQyWebLinksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQyWebLinksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQyWebLinksReply) ProtoMessage() {}

func (x *DeleteQyWebLinksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQyWebLinksReply.ProtoReflect.Descriptor instead.
func (*DeleteQyWebLinksReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{7}
}

type GetQyWebLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQyWebLinksRequest) Reset() {
	*x = GetQyWebLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQyWebLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQyWebLinksRequest) ProtoMessage() {}

func (x *GetQyWebLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQyWebLinksRequest.ProtoReflect.Descriptor instead.
func (*GetQyWebLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{8}
}

type GetQyWebLinksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQyWebLinksReply) Reset() {
	*x = GetQyWebLinksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQyWebLinksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQyWebLinksReply) ProtoMessage() {}

func (x *GetQyWebLinksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQyWebLinksReply.ProtoReflect.Descriptor instead.
func (*GetQyWebLinksReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{9}
}

type ListQyWebLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQyWebLinksRequest) Reset() {
	*x = ListQyWebLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyWebLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyWebLinksRequest) ProtoMessage() {}

func (x *ListQyWebLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyWebLinksRequest.ProtoReflect.Descriptor instead.
func (*ListQyWebLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{10}
}

type ListQyWebLinksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*WebLinkInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListQyWebLinksReply) Reset() {
	*x = ListQyWebLinksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyWebLinksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyWebLinksReply) ProtoMessage() {}

func (x *ListQyWebLinksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyWebLinksReply.ProtoReflect.Descriptor instead.
func (*ListQyWebLinksReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{11}
}

func (x *ListQyWebLinksReply) GetItems() []*WebLinkInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListQyWebShortLinksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*WebShortLinkInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListQyWebShortLinksReply) Reset() {
	*x = ListQyWebShortLinksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQyWebShortLinksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQyWebShortLinksReply) ProtoMessage() {}

func (x *ListQyWebShortLinksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQyWebShortLinksReply.ProtoReflect.Descriptor instead.
func (*ListQyWebShortLinksReply) Descriptor() ([]byte, []int) {
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP(), []int{12}
}

func (x *ListQyWebShortLinksReply) GetItems() []*WebShortLinkInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_qycms_bff_web_v1_qy_web_links_proto protoreflect.FileDescriptor

var file_api_qycms_bff_web_v1_qy_web_links_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2f,
	0x77, 0x65, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x79, 0x5f, 0x77, 0x65, 0x62, 0x5f, 0x6c, 0x69,
	0x6e, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x70, 0x69, 0x2e, 0x71,
	0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a,
	0x0b, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x10, 0x57, 0x65, 0x62, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51,
	0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19,
	0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65,
	0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x51, 0x79, 0x57,
	0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x57, 0x65,
	0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f,
	0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x4c, 0x69,
	0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x58, 0x0a,
	0x18, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x57, 0x65, 0x62, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71,
	0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e,
	0x57, 0x65, 0x62, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xf1, 0x06, 0x0a, 0x0a, 0x51, 0x79, 0x57, 0x65,
	0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x6e, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6e, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6e, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x65, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x51, 0x79, 0x57,
	0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79,
	0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f,
	0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x79,
	0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x92, 0x01,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x57, 0x65, 0x62, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d,
	0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62,
	0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79,
	0x57, 0x65, 0x62, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x77, 0x65, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x12, 0x86, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x57, 0x65, 0x62,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d,
	0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x51, 0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62,
	0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79,
	0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x2f,
	0x76, 0x31, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x61, 0x6c, 0x6c, 0x12, 0x8d, 0x01, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x57, 0x65, 0x62, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4c, 0x69,
	0x6e, 0x6b, 0x73, 0x12, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f,
	0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51,
	0x79, 0x57, 0x65, 0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66,
	0x2e, 0x77, 0x65, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x79, 0x57, 0x65,
	0x62, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1e, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x2f, 0x76, 0x31,
	0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x4e, 0x0a, 0x14, 0x61,
	0x70, 0x69, 0x2e, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66, 0x66, 0x2e, 0x77, 0x65, 0x62,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x77, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x71, 0x69, 0x6e, 0x67, 0x79, 0x75,
	0x63, 0x6d, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x79, 0x63, 0x6d, 0x73, 0x5f, 0x62, 0x66,
	0x66, 0x2f, 0x77, 0x65, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescOnce sync.Once
	file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescData = file_api_qycms_bff_web_v1_qy_web_links_proto_rawDesc
)

func file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescGZIP() []byte {
	file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescOnce.Do(func() {
		file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescData)
	})
	return file_api_qycms_bff_web_v1_qy_web_links_proto_rawDescData
}

var file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_qycms_bff_web_v1_qy_web_links_proto_goTypes = []interface{}{
	(*WebLinkInfo)(nil),              // 0: api.qycms_bff.web.v1.WebLinkInfo
	(*WebShortLinkInfo)(nil),         // 1: api.qycms_bff.web.v1.WebShortLinkInfo
	(*CreateQyWebLinksRequest)(nil),  // 2: api.qycms_bff.web.v1.CreateQyWebLinksRequest
	(*CreateQyWebLinksReply)(nil),    // 3: api.qycms_bff.web.v1.CreateQyWebLinksReply
	(*UpdateQyWebLinksRequest)(nil),  // 4: api.qycms_bff.web.v1.UpdateQyWebLinksRequest
	(*UpdateQyWebLinksReply)(nil),    // 5: api.qycms_bff.web.v1.UpdateQyWebLinksReply
	(*DeleteQyWebLinksRequest)(nil),  // 6: api.qycms_bff.web.v1.DeleteQyWebLinksRequest
	(*DeleteQyWebLinksReply)(nil),    // 7: api.qycms_bff.web.v1.DeleteQyWebLinksReply
	(*GetQyWebLinksRequest)(nil),     // 8: api.qycms_bff.web.v1.GetQyWebLinksRequest
	(*GetQyWebLinksReply)(nil),       // 9: api.qycms_bff.web.v1.GetQyWebLinksReply
	(*ListQyWebLinksRequest)(nil),    // 10: api.qycms_bff.web.v1.ListQyWebLinksRequest
	(*ListQyWebLinksReply)(nil),      // 11: api.qycms_bff.web.v1.ListQyWebLinksReply
	(*ListQyWebShortLinksReply)(nil), // 12: api.qycms_bff.web.v1.ListQyWebShortLinksReply
}
var file_api_qycms_bff_web_v1_qy_web_links_proto_depIdxs = []int32{
	0,  // 0: api.qycms_bff.web.v1.ListQyWebLinksReply.items:type_name -> api.qycms_bff.web.v1.WebLinkInfo
	1,  // 1: api.qycms_bff.web.v1.ListQyWebShortLinksReply.items:type_name -> api.qycms_bff.web.v1.WebShortLinkInfo
	2,  // 2: api.qycms_bff.web.v1.QyWebLinks.CreateQyWebLinks:input_type -> api.qycms_bff.web.v1.CreateQyWebLinksRequest
	4,  // 3: api.qycms_bff.web.v1.QyWebLinks.UpdateQyWebLinks:input_type -> api.qycms_bff.web.v1.UpdateQyWebLinksRequest
	6,  // 4: api.qycms_bff.web.v1.QyWebLinks.DeleteQyWebLinks:input_type -> api.qycms_bff.web.v1.DeleteQyWebLinksRequest
	8,  // 5: api.qycms_bff.web.v1.QyWebLinks.GetQyWebLinks:input_type -> api.qycms_bff.web.v1.GetQyWebLinksRequest
	10, // 6: api.qycms_bff.web.v1.QyWebLinks.ListQyWebShortLinks:input_type -> api.qycms_bff.web.v1.ListQyWebLinksRequest
	10, // 7: api.qycms_bff.web.v1.QyWebLinks.ListQyWebLinks:input_type -> api.qycms_bff.web.v1.ListQyWebLinksRequest
	10, // 8: api.qycms_bff.web.v1.QyWebLinks.ListQyWebIndexLinks:input_type -> api.qycms_bff.web.v1.ListQyWebLinksRequest
	3,  // 9: api.qycms_bff.web.v1.QyWebLinks.CreateQyWebLinks:output_type -> api.qycms_bff.web.v1.CreateQyWebLinksReply
	5,  // 10: api.qycms_bff.web.v1.QyWebLinks.UpdateQyWebLinks:output_type -> api.qycms_bff.web.v1.UpdateQyWebLinksReply
	7,  // 11: api.qycms_bff.web.v1.QyWebLinks.DeleteQyWebLinks:output_type -> api.qycms_bff.web.v1.DeleteQyWebLinksReply
	9,  // 12: api.qycms_bff.web.v1.QyWebLinks.GetQyWebLinks:output_type -> api.qycms_bff.web.v1.GetQyWebLinksReply
	12, // 13: api.qycms_bff.web.v1.QyWebLinks.ListQyWebShortLinks:output_type -> api.qycms_bff.web.v1.ListQyWebShortLinksReply
	11, // 14: api.qycms_bff.web.v1.QyWebLinks.ListQyWebLinks:output_type -> api.qycms_bff.web.v1.ListQyWebLinksReply
	11, // 15: api.qycms_bff.web.v1.QyWebLinks.ListQyWebIndexLinks:output_type -> api.qycms_bff.web.v1.ListQyWebLinksReply
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_qycms_bff_web_v1_qy_web_links_proto_init() }
func file_api_qycms_bff_web_v1_qy_web_links_proto_init() {
	if File_api_qycms_bff_web_v1_qy_web_links_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebLinkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebShortLinkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQyWebLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQyWebLinksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyWebLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQyWebLinksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQyWebLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQyWebLinksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQyWebLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQyWebLinksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyWebLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyWebLinksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQyWebShortLinksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_qycms_bff_web_v1_qy_web_links_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_qycms_bff_web_v1_qy_web_links_proto_goTypes,
		DependencyIndexes: file_api_qycms_bff_web_v1_qy_web_links_proto_depIdxs,
		MessageInfos:      file_api_qycms_bff_web_v1_qy_web_links_proto_msgTypes,
	}.Build()
	File_api_qycms_bff_web_v1_qy_web_links_proto = out.File
	file_api_qycms_bff_web_v1_qy_web_links_proto_rawDesc = nil
	file_api_qycms_bff_web_v1_qy_web_links_proto_goTypes = nil
	file_api_qycms_bff_web_v1_qy_web_links_proto_depIdxs = nil
}
